version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: chat-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: chatting
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - chat-mysql:/var/lib/mysql

  zookeeper-1:
    image: confluentinc/cp-zookeeper:7.9.0
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    volumes:
      - chat-zookeeper:/var/lib/zookeeper

volumes:
  chat-mysql:
  chat-zookeeper: